import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex-provider";

import ModalProvider from "@/components/providers/model-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <EdgeStoreProvider>
          <Toaster position="bottom-right" closeButton />
          <ModalProvider></ModalProvider>
          <body className={inter.className}>{children}</body>
        </EdgeStoreProvider>
      </ConvexClientProvider>
    </html>
  );
}
